# frozen_string_literal: true

source 'https://art-bobcat.autodesk.com/artifactory/api/gems/autodesk-gems-virtual'

ruby '>= 2.7'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'bootsnap', '~> 1.8', '>= 1.8.1'
gem 'listen', '~> 3', '>= 3.7.0'
gem 'rails', '~> 6.0.4.1'
gem 'rails-html-sanitizer', '~> 1', '>= 1.4.2'

gem 'oj', '3.12.1'

gem 'rubyzip', '~> 2.3'
gem 'zip-zip', '~> 0.3'

group :development, :test do
  gem 'byebug', '~> 11'
  gem 'pry-byebug', '~> 3.9'
  gem 'pry-rails', '~> 0.3.6'
  gem 'parallel_tests', '~> 3', '>= 3.7.0'
end

gem 'aws-sdk-s3', '~> 1', '>= 1.100.0'
gem 'launchdarkly-server-sdk', '6.2.2', require: ENV['LD_SDK_KEY'].nil?
gem 'http', '4.4.1'
gem 'ld-eventsource', '2.0.0'
# Dotenv require
gem 'dotenv-rails', '~> 2.7', '>= 2.7.5', require: %w[dotenv/load dotenv/rails-now]
gem 'enumerize', '~> 2', '>= 2.4.0'
gem 'json-schema', '~> 2.8', '>= 2.8.1'

group :development do
  gem 'annotate', '~> 3', '>= 3.1.1'
  gem 'better_errors', '~> 2.8', '>= 2.8.3'
  gem 'binding_of_caller', '~> 1.0.0'
  gem 'derailed_benchmarks', '~> 2.1'
  gem 'rubocop', '~> 1', '>= 1.20.0', require: false
  gem 'rubocop-performance', '~> 1', '>= 1.11.4', require: false
  gem 'rubocop-rails', '~> 2', '>= 2.11.3', require: false
  gem 'rubocop-rspec', '~> 2.4', require: false
end

group :development, :production do
  gem 'foreman', '~> 0.87.0', require: false
  gem 'puma', '~> 5.4', '>= 5.4.0'
  gem 'puma_worker_killer', '~> 0.3', '>= 0.3.1'
end

group :test do
  gem 'factory_bot_rails', '~> 6.2'
  gem 'ffaker', '~> 2', '>= 2.19.0'
  # rspec test frame work
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.4'
  gem 'rspec-json_expectations', '~> 2.2'
  gem 'rspec-rails', '~> 5.0', '>= 5.0.1'
  gem 'shoulda-matchers', '~> 5', '>= 5.0.0', require: false

  gem 'json_expressions', '~> 0.9.0'
  gem 'mongoid-rspec', '~> 4.1'
  gem 'simplecov', '~> 0.21.2'
  gem 'simplecov-cobertura', '~> 1.4', '>= 1.4.1'
  gem 'timecop', '~> 0.9.4'
  gem 'webmock', '~> 3', '>= 3.14.0', require: false
end

# SSO required gems
gem 'oauth', '~> 0.5.4'
gem 'omniauth', '~> 2', '>= 2.0.3'
gem 'omniauth-rails_csrf_protection', '~> 1.0'
gem 'omniauth-saml', '~> 2', '>= 2.0.0'
gem 'omniauth-oauth2', '~> 1.7', '>= 1.7.1'
gem 'rack-cors', '~> 1.1', '>= 1.1.1'
gem 'rack-openid', '~> 1.4', '>= 1.4.2'
gem 'rack-utf8_sanitizer', '~> 1.6'

# Serializer JSON data
gem 'active_model_serializers', '~> 0.10.12'
gem 'grape-entity', '~> 0.9.0'

# Postgres DB
gem 'pg', '~> 1.2', '>= 1.2.3'
gem 'pg_ltree', '~> 1.1', '>= 1.1.8'
# DocumentDB
gem 'mongoid', '~> 7.3'

# logger
gem 'logging', '~> 2.3'
gem 'lograge', '~> 0.11.2'
gem 'logstop', '~> 0.2.7'
gem 'silencer', '~> 1.0', '>= 1.0.1', require: 'silencer/logger'

# authorization
gem 'pundit', '~> 1.1'

gem 'daemons', '~> 1', '>= 1.4.1'
# Doorkeeper for auth
gem 'doorkeeper', '~> 5.5', '>= 5.5.2'

# Sidekiq and Plugin
gem 'activejob-status', '~> 0.1.6'
gem 'sidekiq', '~> 6.2.1'
gem 'sidekiq-enqueuer', '~> 2.1', '>= 2.1.1'
gem 'sidekiq-grouping', '~> 1.0'
gem 'sidekiq-scheduler', '~> 3.1'
gem 'sidekiq-statistic', '~> 1.4'
gem 'sidekiq-status', '~> 2'
gem 'attentive_sidekiq', '~> 0.3.3'
gem 'sidekiq-throttled', '~> 0.12', '>= 0.12.0'
gem 'sidekiq-unique-jobs', '~> 7.0', '>= 7.0.12'
gem 'sidekiq-worker-killer', '~> 1', require: 'sidekiq/worker_killer'

# multi language support
gem 'http_accept_language', '~> 2.1', '>= 2.1.1'

basedir = File.expand_path('.', __dir__)
source "file://#{basedir}/vendor/gems/" do
  gem 'adsk-unified-logging', '~> 1', require: (
    ENV.fetch('UNIFIED_LOGGING_ENABLED', false) ? 'adsk/unified_logging' : false
  )
end

# redis for storage and job queue
gem 'connection_pool', '~> 2.2', '>= 2.2.5'
gem 'redis', '~> 4', '>= 4.3.1'
gem 'redis-namespace', '>= 1.8'
gem 'redis-objects', '~> 1.5'
gem 'redis-rack-cache', '~> 2.2', '>= 2.2.1'
gem 'redis-rails', '~> 5.0', '>= 5.0.2'
gem 'redis-session-store', '~> 0.11.1' # Use redis as session store
gem 'msgpack', '~> 1.3', '>= 1.3.3'
# FTP
gem 'bcrypt_pbkdf', '~> 1', '>= 1.0.1'
gem 'ed25519', '~> 1.2', '>= 1.2.4'
gem 'net-sftp', '~> 3'

# Monitor gems
gem 'ls-trace', '~> 0.2', require: 'ddtrace'
gem 'newrelic_rpm', '~> 6.1', '>= 6.15.0'

# Monitor
unless ENV['REGION'] == 'FEDRAMP'
  gem 'sentry-ruby', '~> 4.6'
  gem 'sentry-rails', '~> 4.6'
  gem 'sentry-sidekiq', '~> 4.6'
end

gem 'parallel', '~> 1.19', '>= 1.19.2'

gem 'activerecord-import', '~> 1', '>= 1.2.0'

gem 'wannabe_bool', '~> 0.7.0'

# https://github.com/typhoeus/typhoeus
# fast and reliable requests, for parallel request
gem 'typhoeus', '~> 1'

gem 'browser', '~> 5.3', '>= 5.3.1'

gem 'ruby_http_client', '~> 3.5'
gem 'sendgrid-actionmailer', '~> 3.2'
gem 'sendgrid-ruby', '~> 6', '>= 6.5.0'
gem 'adsk_activity', '0.1', path: 'vendor/gems/adsk_activity'
gem 'forge_model', '~> 0.1.0', path: 'vendor/gems/forge_model'

# for writing zipkin log to kafka
# comment out this kafka feature for its memory leak
# gem 'ruby-kafka'
gem 'concurrent-ruby-ext', '~> 1.1', '>= 1.1.9'
gem 'slack-notifier', '~> 2.4'
gem 'uuidtools', '~> 2.2'
